'''
Created on 16 Apr 2017

@author: rweffercifue
'''

DELETE_MARK = "DELETE MARK"
CLEAR_MARKS = "CLEAR MARKS"
MEASUREMENTS_DONE = "MEASUREMENTS DONE" 
MEASUREMENTS_DONE_REP = "MEASUREMENTS DONE REPETITION" 
EXIT = "EXIT"
NEXT = " NEXT"
OUT_OF_BOUNDS = "OUT_OF_BOUNDS"

START = "START"
OPEN = "OPEN"
CREATE = "CREATE"
SAVE = "SAVE"